# -------------------------------
# Frontend Dockerfile (Static HTML/JS)
# -------------------------------

FROM nginx:alpine

# Copy frontend files into nginx public folder
COPY . /usr/share/nginx/html

# Expose port 80 for frontend
EXPOSE 80